SixLabors/ImageSharp.Drawing

ImageSharp.Drawing.sln, tests/ImageSharp.Tests/ImageSharp.Drawing.Tests.csproj, tests/ImageSharp.Tests/Shapes/ComplexPolygonTests.cs
- Remove x86 and x64 solution platforms
- Copy `SixLaborsSampleAB.woff` to out dir
- Switch to a different `string.Join` overload to avoid mysterious build failures
=> Minor cleanup and fix failing tests

src/ImageSharp.Drawing/Processing/Processors/Text/DrawTextProcessor{TPixel}.cs, src/ImageSharp.Drawing/Shapes/ComplexPolygon.cs, src/ImageSharp.Drawing/Shapes/InternalPath.cs, tests/ImageSharp.Drawing.Tests/Drawing/Text/DrawTextOnImageTests.cs, tests/ImageSharp.Drawing.Tests/Shapes/ComplexPolygonTests.cs
Ensure we render glyphs using nonzero rule to prevent holes when using certain fonts.
Also fixed a side issue when starting trying to render a glyph completely to the left/above the image.
Fixes #35
=> Render glyphs with nonzero IntersectionRule

src/ImageSharp.Drawing/Processing/Processors/Drawing/FillPathProcessor.cs, tests/ImageSharp.Drawing.Tests/Processing/FillPathProcessorTests.cs
This special cases Filling `RectangularPolygon`s if it lines up exactly to int boundries or  anti-aliasing is off then it uses the `FillProcessor` rather than the slower `FillRegionProcessor` (which deals with anti-alising and rasterization)
Fixes #40
Dependent on #39
=> Optermization for filling rectangles to gain access to fast fill path

src/ImageSharp.Drawing/Shapes/InternalPath.cs, tests/ImageSharp.Drawing.Tests/Issues/Issues-48.cs
This adds logic to `InternalPath` to cope with paths with zero length.
Resolves #48 
Resolves #47
=> Prevent internal path throwing index out of range for an empty path

src/ImageSharp.Drawing/Shapes/InternalPath.cs, tests/ImageSharp.Drawing.Tests/Issues/Issues-55-59.cs
`InternalPath` is attempting to use an out of range index when the length of the simplified point array is 1.
I assumed that the rest of the reduction code is sound and that since the previous logic assigned a segment with two identical values, simply reusing the value at `0` was ok. 
This fixes #55, and fixes #59
=> Check length before using index.

src/ImageSharp.Drawing/Processing/Processors/Drawing/FillProcessor{TPixel}.cs, tests/ImageSharp.Drawing.Tests/Issues/Issue_65.cs
=> Skip filling rectangles if the effective fill area is zero width or height

.github/workflows/build-and-test.yml, Directory.Build.props, Directory.Build.targets, GitVersion.yml, ci-build.ps1, ci-pack.ps1, src/Directory.Build.props, src/Directory.Build.targets, src/ImageSharp.Drawing/ImageSharp.Drawing.csproj, tests/Directory.Build.targets
This is a port of the minver changes applied to the main ImageSharp repo as i'm getting sick of the gitversion randomly failing on some of the builds
=> drop gitversion in favour of minver

.github/CONTRIBUTING.md, .github/ISSUE_TEMPLATE/config.yml, .github/PULL_REQUEST_TEMPLATE.md
Github changed the links path so our template links are returning 404. I've updated that and also fixed a couple of other docs issues.
=> Fix contribution links

.github/workflows/build-and-test.yml, src/Directory.Build.props, src/Directory.Build.targets
Same thing as SixLabors/ImageSharp#1337. My Rider is configured with .NET 5 SDK so I need this now.
=> Fix compatibility with .NET 5 SDK InternalsVisibleTo

src/ImageSharp.Drawing/Shapes/Rasterization/PolygonScanner.cs, tests/ImageSharp.Drawing.Tests/Issues/Issue_28.cs, tests/ImageSharp.Drawing.Tests/Issues/Issue_28_108.cs, tests/ImageSharp.Drawing.Tests/Shapes/Scan/PolygonScannerTests.cs
Updates `PolygonScanner` to correctly handle  scanlines outside of the image frame. Lines are still centered correctly.
Fixes #108 
[Angle starting and finishing outside of the frame](https://github.com/OleksandrKrutykh)
Stroke 3 Top
Stroke 3 Bottom
Stroke 3 Left
Stroke 3 Right
=> Fix IndexOutOfRangeException when drawing lines outside of image

.github/workflows/build-and-test.yml, ci-pack.ps1
There's something funny going on with versioning for .NET Core 3.1. See #137 
I've checked and none of our other repositories are affected so I'm assuming (hoping) it's something to do with this repositories git history
Looking at the publish step there's a warning that the project directory is not a valid git folder. I'm going to see if simplifying the process to use standard action options fixes the issue.
https://github.com/SixLabors/ImageSharp.Drawing/runs/2644202851?check_suite_focus=true#step:5:82
=> Fix Build Process.

src/ImageSharp.Drawing/Processing/BrushApplicator.cs
Fixes #20 allowing custom brushes inheriting `BrushApplicator`
=> Allow implementing custom brush types

src/ImageSharp.Drawing/Processing/ImageBrush.cs, src/ImageSharp.Drawing/Processing/Processors/Drawing/RecursiveImageProcessor.cs, tests/ImageSharp.Drawing.Tests/Drawing/ClipTests.cs, tests/ImageSharp.Drawing.Tests/Drawing/FillPolygonTests.cs, tests/Images/ReferenceOutput/Drawing/ClipTests/Clip_offset_x40_y60.png, tests/Images/ReferenceOutput/Drawing/FillPolygonTests/FillPolygon_ImageBrush_Rect_Rgba32_Car_rect.png, tests/Images/ReferenceOutput/Drawing/FillPolygonTests/FillPolygon_ImageBrush_Rect_Rgba32_ducky_rect.png
@JimBobSquarePants  This is just the changes for you #150 branch that correctly clips the source image while still supporting target/destination offsetting (that's what the pre-existing region was for).
NOTE@ This is targeting branch of #150
=> enable image brush to be only draw a portion of the source image

src/ImageSharp.Drawing/Processing/ShapeOptions.cs, src/ImageSharp.Drawing/Processing/TextOptions.cs
Some defaults value documentation were wrong. Also, `<para/>` was added to make the defaults stand out.
Before this pull request:
After this pull request:
=> Fix defaults documentation of ShapeOptions and TextOptions properties

.github/workflows/build-and-test.yml, ImageSharp.Drawing.sln, ci-build.ps1, ci-pack.ps1, samples/Directory.Build.props, samples/Directory.Build.targets, samples/DrawShapesWithImageSharp/DrawShapesWithImageSharp.csproj, samples/DrawShapesWithImageSharp/ImageSharpLogo.cs, samples/DrawShapesWithImageSharp/Program.cs, samples/Drawing.Samples.ruleset, src/ImageSharp.Drawing/Shapes/PathExtensions.cs, tests/ImageSharp.Drawing.Tests/Drawing/Paths/ComputeLength.cs
Updates the samples project to use the latest API and includes it in the solution so we don't forget about it in the future.
=> Update samples and add to main solution

samples/DrawShapesWithImageSharp/Program.cs, src/ImageSharp.Drawing/ImageSharp.Drawing.csproj, tests/ImageSharp.Drawing.Tests/Drawing/Text/DrawText.cs, tests/ImageSharp.Drawing.Tests/Issues/Issue_46.cs, tests/ImageSharp.Drawing.Tests/Issues/Issue_54.cs, tests/ImageSharp.Drawing.Tests/TestFontUtilities.cs
Updates the Fonts ref to use the latest `FontCollection` API
=> Update Fonts to use new API

src/ImageSharp.Drawing/ImageSharp.Drawing.csproj, src/ImageSharp.Drawing/Processing/Processors/Text/DrawTextProcessor{TPixel}.cs, src/ImageSharp.Drawing/Processing/TextOptions.cs, tests/Images/ReferenceOutput/Drawing/Text/DrawTextOnImageTests/FontShapesAreRenderedCorrectly_WithLineSpacing_linespacing_1.5_linecount_3_wrap_True.png, tests/Images/ReferenceOutput/Drawing/Text/DrawTextOnImageTests/FontShapesAreRenderedCorrectly_WithLineSpacing_linespacing_1_linecount_5_wrap_True.png, tests/Images/ReferenceOutput/Drawing/Text/DrawTextOnImageTests/FontShapesAreRenderedCorrectly_WithLineSpacing_linespacing_2_linecount_2_wrap_True.png
Bumps the underlying fonts version so we can use the new word breaking options.
=> Add wordbreaking support

src/ImageSharp.Drawing/ImageSharp.Drawing.csproj, src/ImageSharp.Drawing/Shapes/Text/TextBuilder.cs, tests/ImageSharp.Drawing.Tests/ConfigurationTests.cs, tests/ImageSharp.Drawing.Tests/Shapes/TextBuilderTests.cs
Drawing text via `TextBuilder` was incorrectly double offsetting the input if the `TextOptions` contained an origin when compared to `DrawText`.
I've also updated our refs to the latest MyGet builds to ensure we are testing against recent changes.
CC @Turnerj
=> Remove double origin assignment from TextBuilder

src/ImageSharp.Drawing/Shapes/Rasterization/RasterizerExtensions.cs, tests/ImageSharp.Drawing.Tests/Shapes/Scan/RasterizerExtensionsTests.cs, tests/Images/ReferenceOutput/Drawing/FillPolygonTests/Fill_RectangularPolygon_Solid_TransformedUsingConfiguration_Rgba32_BasicTestPattern100x100.png, tests/Images/ReferenceOutput/Drawing/FillPolygonTests/Fill_RectangularPolygon_Solid_Transformed_Rgba32_BasicTestPattern100x100.png, tests/Images/ReferenceOutput/RasterizerExtensionsTests/AntialiasingIsAntialiased_Rgba32_Solid400x75_(255,255,255,255).png
When rasterizing scanlines where the intersection with the region (any where on the line) is less than a pixel wide we had a bug that would reset the `scanlineDirty`. it should only ever be possible to flip the bit to true and never false in the region of changed code.
How this ended up manifesting is when drawing a shape (seen usually in text) of a pixel wide you would see antialias artefacts even with it disabled.
Before
After
resolves #203
=> Prevent a subpixel being able to reset dirty flag

src/ImageSharp.Drawing/ImageSharp.Drawing.csproj, src/ImageSharp.Drawing/Shapes/Rasterization/PolygonScanner.cs, src/ImageSharp.Drawing/Shapes/Rasterization/ScanEdgeCollection.cs, tests/ImageSharp.Drawing.Tests/Drawing/Text/DrawTextOnImageTests.cs, tests/ImageSharp.Drawing.Tests/MemoryAllocatorValidator.cs, tests/ImageSharp.Drawing.Tests/Shapes/Scan/ScanEdgeCollectionTests.cs, tests/ImageSharp.Drawing.Tests/TestFormat.cs, tests/ImageSharp.Drawing.Tests/TestUtilities/ImageProviders/FileProvider.cs, tests/ImageSharp.Drawing.Tests/TestUtilities/ReferenceCodecs/MagickReferenceDecoder.cs, tests/ImageSharp.Drawing.Tests/TestUtilities/ReferenceCodecs/SystemDrawingReferenceDecoder.cs, tests/ImageSharp.Drawing.Tests/TestUtilities/Tests/TestImageProviderTests.cs, tests/ImageSharp.Drawing.Tests/ValidateDisposedMemoryAllocationsAttribute.cs
Like with SixLabors/ImageSharp#2082 this introduces the test helpers for validating Memory allocations tracked by our memory allocator.
~This is dependent on the code in SixLabors/ImageSharp#2082 for the required changes to the `MemoryDiagnostics` class to enable this.~ Merged
Also fixes #215
=> Track memory allocations in tests

src/ImageSharp.Drawing/Shapes/EmptyPath.cs, src/ImageSharp.Drawing/Shapes/OutlinePathExtensions.cs, src/ImageSharp.Drawing/Shapes/Path.cs, tests/ImageSharp.Drawing.Tests/Shapes/Issues/Issue_224.cs
Updates the `GenerateOutline` extensions so that when an invalid width (<= 0) is specified that instead of looping it returns an `EmptyPath` (a new type to represent an empty path without addition allocations).
This resolves #224
=> Return empty path when outline width is less than or equal to zero

src/ImageSharp.Drawing/Processing/PatternBrush.cs, tests/ImageSharp.Drawing.Tests/Issues/Issue_241.cs
Fixes #241 
This must have been fixed in the rewrite of the brushes. I've added the test from the issue and removed some unused fields from the brush.
=> Add tests for PatterBrush issue 241

src/ImageSharp.Drawing/Processing/PathGradientBrush.cs, src/ImageSharp.Drawing/Shapes/PolygonClipper/BoundsF.cs, src/ImageSharp.Drawing/Shapes/PolygonClipper/ClipperUtils.cs, src/ImageSharp.Drawing/Shapes/PolygonClipper/PolygonClipper.cs
Updates the polygon clipping code to include all relevant upstream fixes.
Also includes some minor cleanup.
=> Clipper upstream fixes

src/ImageSharp.Drawing/Processing/DrawingOptionsDefaultsExtensions.cs, src/ImageSharp.Drawing/Processing/Extensions/ClearExtensions.cs, src/ImageSharp.Drawing/Processing/Extensions/ClearPathExtensions.cs, src/ImageSharp.Drawing/Processing/Extensions/ClearRectangleExtensions.cs, src/ImageSharp.Drawing/Processing/Extensions/ClipPathExtensions.cs, src/ImageSharp.Drawing/Processing/Extensions/DrawBezierExtensions.cs, src/ImageSharp.Drawing/Processing/Extensions/DrawLineExtensions.cs, src/ImageSharp.Drawing/Processing/Extensions/DrawPathCollectionExtensions.cs, src/ImageSharp.Drawing/Processing/Extensions/DrawPathExtensions.cs, src/ImageSharp.Drawing/Processing/Extensions/DrawPolygonExtensions.cs, src/ImageSharp.Drawing/Processing/Extensions/DrawRectangleExtensions.cs, src/ImageSharp.Drawing/Processing/Extensions/DrawTextExtensions.cs, src/ImageSharp.Drawing/Processing/Extensions/FillExtensions.cs, src/ImageSharp.Drawing/Processing/Extensions/FillPathBuilderExtensions.cs, src/ImageSharp.Drawing/Processing/Extensions/FillPathCollectionExtensions.cs, src/ImageSharp.Drawing/Processing/Extensions/FillPathExtensions.cs, src/ImageSharp.Drawing/Processing/Extensions/FillPolygonExtensions.cs, src/ImageSharp.Drawing/Processing/Extensions/FillRectangleExtensions.cs, src/ImageSharp.Drawing/Processing/ShapeGraphicOptionsDefaultsExtensions.cs
=> Normalize XML comments.

samples/DrawShapesWithImageSharp/Program.cs, src/ImageSharp.Drawing/Processing/Extensions/DrawLineExtensions.cs, src/ImageSharp.Drawing/Processing/Extensions/DrawPolygonExtensions.cs, src/ImageSharp.Drawing/Processing/Extensions/FillPolygonExtensions.cs, src/ImageSharp.Drawing/Shapes/Path.cs, src/ImageSharp.Drawing/Shapes/Polygon.cs, src/ImageSharp.Drawing/Shapes/PolygonClipper/Clipper.cs, src/ImageSharp.Drawing/Shapes/PolygonClipper/ClipperOffset.cs, tests/ImageSharp.Drawing.Tests/Shapes/Scan/TessellatedMultipolygonTests.cs
=> Add Convenience Constructors to shapes

src/ImageSharp.Drawing/Shapes/PolygonClipper/Clipper.cs, src/ImageSharp.Drawing/Shapes/Rasterization/ScanEdgeCollection.Build.cs, tests/ImageSharp.Drawing.Benchmarks/Drawing/Rounding.cs
Adds the missing commit from #290 
Removes unnecessary scaling from `PolygonClipper`.
=> Additional drawing performance fixes

src/ImageSharp.Drawing/Shapes/ArcLineSegment.cs, src/ImageSharp.Drawing/Shapes/PolygonClipper/BoundsF.cs, src/ImageSharp.Drawing/Shapes/PolygonClipper/PolygonOffsetter.cs, tests/ImageSharp.Drawing.Tests/Drawing/DrawLinesTests.cs, tests/ImageSharp.Drawing.Tests/Drawing/DrawPathTests.cs, tests/ImageSharp.Drawing.Tests/Shapes/PolygonClipper/ClipperTests.cs, tests/Images/ReferenceOutput/Drawing/DrawLinesTests/DrawLinesInvalidPoints_Rgba32_T(1).png, tests/Images/ReferenceOutput/Drawing/DrawLinesTests/DrawLinesInvalidPoints_Rgba32_T(1)_NoAntialias.png, tests/Images/ReferenceOutput/Drawing/DrawLinesTests/DrawLinesInvalidPoints_Rgba32_T(5).png, tests/Images/ReferenceOutput/Drawing/DrawLinesTests/DrawLinesInvalidPoints_Rgba32_T(5)_NoAntialias.png, tests/Images/ReferenceOutput/Drawing/DrawPathTests/DrawCircleUsingAddArc_359.png, tests/Images/ReferenceOutput/Drawing/DrawPathTests/DrawCircleUsingAddArc_360.png, tests/Images/ReferenceOutput/Drawing/DrawPathTests/DrawCircleUsingArcTo_False.png, tests/Images/ReferenceOutput/Drawing/DrawPathTests/DrawCircleUsingArcTo_True.png
Fixes #299, #300
The way I was handling arc generation when the arc sweep represented a closed ellipse didn't take into consideration the start angle. 
Fixing the issue meant that we threw during outlining when someone requested the short arc so I fixed the offsetter to return the unclipped path I also fixed the handling of paths containing a single point.
=> Fix arcs and do not throw when outlining

src/ImageSharp.Drawing/Processing/GradientBrush.cs, src/ImageSharp.Drawing/Processing/Processors/Text/DrawTextProcessor{TPixel}.cs, tests/ImageSharp.Drawing.Tests/Drawing/Text/DrawTextOnImageTests.cs, tests/Images/ReferenceOutput/Drawing/Text/DrawTextOnImageTests/CanRenderTextOutOfBoundsIssue301.png
Fixes #301 
The `DrawTextProcessor` allowed rendered buffers that exceeded the width of the image frame. This PR clamps the length of the span passed to the brush applicator. Our other processors correctly limit the span length.
I also added colorstop stable sorting to the gradient brush since I spotted the TODO while debugging.
=> Fix Out of Bounds Text Drawing

src/ImageSharp.Drawing/Processing/ImageBrush.cs, tests/ImageSharp.Drawing.Tests/Drawing/FillImageBrushTests.cs, tests/Images/ReferenceOutput/Drawing/FillImageBrushTests/CanDrawNegativeOffsetImage_Rgba32.png
See #305 The public constructor is required to selecting the source region providing the ability to negative offset and image.
=> Expose ImageBrush source region constructor.

src/ImageSharp.Drawing/Shapes/OutlinePathExtensions.cs, tests/ImageSharp.Drawing.Tests/Issues/Issue_323.cs, tests/Images/ReferenceOutput/Issue_323/DrawPolygonMustDrawoutlineOnly_Pattern_Rgba32_Solid300x300_(255,255,255,255)_scale-0.003.png, tests/Images/ReferenceOutput/Issue_323/DrawPolygonMustDrawoutlineOnly_Pattern_Rgba32_Solid300x300_(255,255,255,255)_scale-0.3.png, tests/Images/ReferenceOutput/Issue_323/DrawPolygonMustDrawoutlineOnly_Pattern_Rgba32_Solid300x300_(255,255,255,255)_scale-0.7.png, tests/Images/ReferenceOutput/Issue_323/DrawPolygonMustDrawoutlineOnly_Pattern_Rgba32_Solid300x300_(255,255,255,255)_scale-1.png, tests/Images/ReferenceOutput/Issue_323/DrawPolygonMustDrawoutlineOnly_Pattern_Rgba32_Solid300x300_(255,255,255,255)_scale-3.png, tests/Images/ReferenceOutput/Issue_323/DrawPolygonMustDrawoutlineOnly_Rgba32_Solid300x300_(255,255,255,255)_scale-0.003.png, tests/Images/ReferenceOutput/Issue_323/DrawPolygonMustDrawoutlineOnly_Rgba32_Solid300x300_(255,255,255,255)_scale-0.3.png, tests/Images/ReferenceOutput/Issue_323/DrawPolygonMustDrawoutlineOnly_Rgba32_Solid300x300_(255,255,255,255)_scale-0.7.png, tests/Images/ReferenceOutput/Issue_323/DrawPolygonMustDrawoutlineOnly_Rgba32_Solid300x300_(255,255,255,255)_scale-1.png, tests/Images/ReferenceOutput/Issue_323/DrawPolygonMustDrawoutlineOnly_Rgba32_Solid300x300_(255,255,255,255)_scale-3.png
If the outline thickness is going to trigger the noop behaviour of the clipper then scale the inputs and outputs to not trigger that behaviour.
I tried just removing the test in [`PolygonOffsetter.cs`](https://github.com/SixLabors/ImageSharp.Drawing/blob/2a9ee5150addbf280801ed25392a8ec29eb8e263/src/ImageSharp.Drawing/Shapes/PolygonClipper/PolygonOffsetter.cs#L121) but for some reason  that causes very small outlines to take significantly longer to generate than scaling up and down. (not investigated why).
This causes everything to generally render now, what it renders at particularly small sizes might not be the best (not investigated) but at least we generally render something better than the solid shape.
resolves #323
=> Mitigate issue where outline thicknesses less than 0.5 fail out generate solid shapes not outlines

src/ImageSharp.Drawing/ImageSharp.Drawing.csproj, tests/ImageSharp.Drawing.Tests/Drawing/Text/DrawTextOnImageTests.cs, tests/Images/ReferenceOutput/Drawing/Text/DrawTextOnImageTests/CanRotateFilledFont_Issue175_Solid300x200_(255,255,255,255)_F(OpenSans-Regular.ttf)-S(32)-A(75)-Quic).png, tests/Images/ReferenceOutput/Drawing/Text/DrawTextOnImageTests/CanRotateFilledFont_Issue175_Solid300x200_(255,255,255,255)_F(OpenSans-Regular.ttf)-S(40)-A(90)-Quic).png, tests/Images/ReferenceOutput/Drawing/Text/DrawTextOnImageTests/CanRotateOutlineFont_Issue175_Solid300x200_(255,255,255,255)_F(OpenSans-Regular.ttf)-S(32)-A(75)-STR(1)-Quic).png, tests/Images/ReferenceOutput/Drawing/Text/DrawTextOnImageTests/CanRotateOutlineFont_Issue175_Solid300x200_(255,255,255,255)_F(OpenSans-Regular.ttf)-S(40)-A(90)-STR(2)-Quic).png
=> Update Fonts to v2.0.3 and ImageSharp to v3.1.4

.github/workflows/build-and-test.yml, src/ImageSharp.Drawing/Processing/Processors/Text/RichTextGlyphRenderer.cs, tests/ImageSharp.Drawing.Tests/Issues/Issue_330.cs, tests/ImageSharp.Drawing.Tests/TestFontUtilities.cs, tests/Images/ReferenceOutput/Drawing/Text/DrawTextOnImageTests/CanRotateOutlineFont_Issue175_Solid300x200_(255,255,255,255)_F(OpenSans-Regular.ttf)-S(40)-A(90)-STR(2)-Quic).png, tests/Images/ReferenceOutput/Drawing/Text/DrawTextOnImageTests/FontShapesAreRenderedCorrectlyWithAPenPatterned_Solid1100x200_(255,255,255,255)_pen_OpenSans-Regular.ttf-50-Sphi-(150,50).png, tests/Images/ReferenceOutput/Drawing/Text/DrawTextOnImageTests/FontShapesAreRenderedCorrectlyWithAPenPatterned_Solid200x150_(255,255,255,255)_pen_SixLaborsSampleAB.woff-50-ABAB-(0,0).png, tests/Images/ReferenceOutput/Drawing/Text/DrawTextOnImageTests/FontShapesAreRenderedCorrectlyWithAPenPatterned_Solid900x150_(255,255,255,255)_pen_OpenSans-Regular.ttf-50-Sphi-(0,0).png, tests/Images/ReferenceOutput/Issue_330/OffsetTextOutlines_Rgba32_Solid2084x2084_(138,43,226,255).png
fixes the outline being offset from the fill.
Required the outline being moved (thickness/2) pixels up and left.
fixes #330
=> Align font outline and fill while calling DrawText

src/ImageSharp.Drawing/ImageSharp.Drawing.csproj, src/ImageSharp.Drawing/Processing/RichTextOptions.cs, tests/ImageSharp.Drawing.Tests/Issues/Issue_332.cs, tests/Images/ReferenceOutput/Drawing/Text/DrawTextOnImageTests/CanRotateFilledFont_Issue175_Solid300x200_(255,255,255,255)_F(OpenSans-Regular.ttf)-S(32)-A(75)-Quic).png, tests/Images/ReferenceOutput/Drawing/Text/DrawTextOnImageTests/CanRotateFilledFont_Issue175_Solid300x200_(255,255,255,255)_F(OpenSans-Regular.ttf)-S(40)-A(90)-Quic).png, tests/Images/ReferenceOutput/Drawing/Text/DrawTextOnImageTests/CanRotateOutlineFont_Issue175_Solid300x200_(255,255,255,255)_F(OpenSans-Regular.ttf)-S(32)-A(75)-STR(1)-Quic).png, tests/Images/ReferenceOutput/Drawing/Text/DrawTextOnImageTests/CanRotateOutlineFont_Issue175_Solid300x200_(255,255,255,255)_F(OpenSans-Regular.ttf)-S(40)-A(90)-STR(2)-Quic).png, tests/Images/ReferenceOutput/Drawing/Text/DrawTextOnImageTests/FallbackFontRendering_Rgba32_Solid400x200_(255,255,255,255).png
ImageSharp v3.1.5
Fonts v2.0.4
=> Update references and fix casting of RichTextRuns

ImageSharp.Drawing.sln, src/ImageSharp.Drawing/Processing/RecolorBrush.cs
RecolorBrush didn't take transforms into consideration. I've not added an explicit test but here's the output from the samples project.
=> RecolorBrush  - Limit access to target dimensions

.github/workflows/build-and-test.yml, src/ImageSharp.Drawing/ImageSharp.Drawing.csproj, tests/ImageSharp.Drawing.Tests/Drawing/Text/DrawTextOnImageTests.cs, tests/Images/ReferenceOutput/Drawing/Text/DrawTextOnImageTests/CanDrawTextVerticalMixed_Rgba32_Blank500x400.png, tests/Images/ReferenceOutput/Drawing/Text/DrawTextOnImageTests/CanFillTextVerticalMixed_Rgba32_Blank500x400.png
ImageSharp v3.1.8
Fonts v2.1.3
=> Updates Six Labors References to Latest Versions
