.github/ISSUE_TEMPLATE/config.yml
I had duplicate sections in the file.
=> Fix Issues Yaml

.github/workflows/build-and-test.yml, ci-test.ps1, tests/Directory.Build.props, tests/Directory.Build.targets
Use official (working) CodeCov app
https://github.com/marketplace/actions/codecov
=> Use official CodeCov app

.github/ISSUE_TEMPLATE/config.yml, README.md
=> Update Discussions Links

src/ImageSharp.Drawing/Processing/Pen.cs, src/ImageSharp.Drawing/Shapes/ComplexPolygon.cs, tests/ImageSharp.Drawing.Tests/Issues/Issue-54.cs, tests/ImageSharp.Drawing.Tests/TestUtilities/Attributes/PlatformFactAttribute.cs
=> Prevent issue with zero width pens

.github/FUNDING.yml, .github/workflows/build-and-test.yml, README.md
=> Update sponsorship info

src/ImageSharp.Drawing/ImageSharp.Drawing.csproj
Bump fonts to version supporting line breaker algorithm. Fixes #115
=> Add LineBreaker Algorithm

.github/workflows/build-and-test.yml, ci-pack.ps1
Updates the CI packing to use Ubuntu. Fixes #139
=> Fix MinVer Build Issue

.github/workflows/build-and-test.yml
=> Fix nuget push

.github/workflows/build-and-test.yml
Fixes dotnet nuget command configuration
=> Use correct arguments

.github/workflows/build-and-test.yml
=> Fix API key param

.github/workflows/build-and-test.yml
=> Fix Nuget API Key Config

src/ImageSharp.Drawing/ImageSharp.Drawing.csproj
Simple version bump. Fast-tracking this through without review because the package retention policy deleted the previous dependency
=> Update ImageSharp reference

src/ImageSharp.Drawing/ImageSharp.Drawing.csproj
Just a ref bump in prep for a new beta release.
=> Update refs to latest

src/ImageSharp.Drawing/Shapes/ComplexPolygon.cs
Convenience constructors for shapes #100
=> Add convenience constructor to ComplexPolygon

src/ImageSharp.Drawing/Shapes/PolygonClipper/PolygonClipper.cs
Applies the fix from https://github.com/AngusJohnson/Clipper2/commit/d18faa9a262ea27fcf52e0454611e9a3f8d74f30 to our port.
=> Apply upstream clipper fix 500

src/ImageSharp.Drawing/Processing/ImageBrush.cs, src/ImageSharp.Drawing/Processing/Processors/Text/DrawTextProcessor{TPixel}.cs, tests/ImageSharp.Drawing.Tests/Issues/Issue_270.cs
=> Fix ImageBrush and DrawTextProcessor  

src/ImageSharp.Drawing/ImageSharp.Drawing.csproj, src/ImageSharp.Drawing/Processing/Brushes.cs, src/ImageSharp.Drawing/Processing/Extensions/DrawBezierExtensions.cs, src/ImageSharp.Drawing/Processing/Extensions/DrawPathCollectionExtensions.cs, src/ImageSharp.Drawing/Processing/Extensions/DrawPathExtensions.cs, src/ImageSharp.Drawing/Processing/Extensions/DrawTextExtensions.cs, src/ImageSharp.Drawing/Processing/GradientRepetitionMode.cs, src/ImageSharp.Drawing/Processing/ImageBrush.cs, src/ImageSharp.Drawing/Processing/PatternPen.cs, src/ImageSharp.Drawing/Processing/Pen.cs, src/ImageSharp.Drawing/Processing/Pens.cs, src/ImageSharp.Drawing/Processing/Processors/Text/RichTextGlyphRenderer.cs, src/ImageSharp.Drawing/Processing/RecolorBrush.cs, src/ImageSharp.Drawing/Processing/ShapeGraphicOptionsDefaultsExtensions.cs, src/ImageSharp.Drawing/Processing/SolidBrush.cs, src/ImageSharp.Drawing/Shapes/ClipPathExtensions.cs, src/ImageSharp.Drawing/Shapes/EmptyPath.cs, src/ImageSharp.Drawing/Shapes/PathBuilder.cs, src/ImageSharp.Drawing/Shapes/PathCollection.cs, src/ImageSharp.Drawing/Shapes/PathExtensions.cs, src/ImageSharp.Drawing/Shapes/PolygonClipper/PolygonOffsetter.cs, src/ImageSharp.Drawing/Shapes/RectangularPolygon.cs, src/ImageSharp.Drawing/Shapes/RegularPolygon.cs, src/ImageSharp.Drawing/Shapes/Star.cs, tests/ImageSharp.Drawing.Tests/Shapes/RegularPolygonTests.cs
I added some cleanup to this PR to fix spelling issues. I'll push on as they don't affect the output binary.
=> Update Fonts to v1.0.0

.github/workflows/build-and-test.yml, src/ImageSharp.Drawing/ImageSharp.Drawing.csproj
Bumps ImageSharp to v2.1.5 to include latest security fixes. 
Also adds publishing to the build pipeline.
=> Bump ImageSharp

src/ImageSharp.Drawing/ImageSharp.Drawing.csproj
=> Bump dependencies for V2 release

src/ImageSharp.Drawing/ImageSharp.Drawing.csproj
=> Update to ImageSharp v3.1.1

src/ImageSharp.Drawing/ImageSharp.Drawing.csproj
=> Update to ImageSharp v3.1.11

.github/workflows/build-and-test.yml, src/ImageSharp.Drawing/ImageSharp.Drawing.csproj
- Updates to latest Six Labors dependencies
- Updates workflow to use improved caching of LFS artifacts
- Updates submodule to include license key requirement.
=> Update refs and submodule; update workflow
